# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository/
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  QUARKUS_LOCAL_REPO: $(MAVEN_CACHE_FOLDER)

stages:
  #This stage uses the azure caching feature to reduce the downloads that are performed from central, which greatly speeds up CI
  #This is it's own stage to prevent Quarkus artifacts produced by the build from being cached
  - stage: cache_maven_repo_stage
    displayName: 'Maven Cache'
    jobs:
      - job: Cache_Maven_Repo
        displayName: 'Linux Maven Repo'
        timeoutInMinutes: 30
        pool:
          vmImage: 'Ubuntu 16.04'
        variables:
          imageName: 'quarkus:$(build.buildId)'
        steps:
          - task: CacheBeta@0
            displayName: 'Cache Maven local repo'
            inputs:
              key: maven | pom.xml
              path: $(MAVEN_CACHE_FOLDER)
              securityNamespace: cache
              cacheHitVar: CACHE_RESTORED
          - task: Maven@3
            displayName: 'Maven Build'
            condition: ne(variables.CACHE_RESTORED, 'true')
            inputs:
              goals: 'package'
              mavenOptions: $(MAVEN_OPTS)
              options: '-B --settings azure-mvn-settings.xml -DskipTests=true -Dno-format'
      - job: Cache_Windows_Maven_Repo #windows has different line endings so the cache key is different
        displayName: 'Windows Maven Repo'
        timeoutInMinutes: 30
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          imageName: 'quarkus-windows:$(build.buildId)'
        steps:
          - task: CacheBeta@0
            displayName: 'Cache Maven local repo'
            inputs:
              key: mavenWindows | pom.xml
              path: $(MAVEN_CACHE_FOLDER)
              securityNamespace: cache
              cacheHitVar: CACHE_RESTORED
          - task: Maven@3
            displayName: 'Maven Build'
            condition: ne(variables.CACHE_RESTORED, 'true')
            inputs:
              goals: 'package'
              mavenOptions: $(MAVEN_OPTS)
              options: '-B --settings azure-mvn-settings.xml -DskipTests=true -Dno-format'